-- MySQL Script generated by MySQL Workbench
-- Sat Aug 17 00:27:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ref_Customer_Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Customer_Types` (
  `PK customer_type_code` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL DEFAULT 'Civil',
  PRIMARY KEY (`PK customer_type_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `PK customer_id` INT NOT NULL AUTO_INCREMENT,
  `FK customer_type_code` INT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `date_became_customer` DATE NULL,
  `date_quit_customer` DATE NULL,
  `other_details` VARCHAR(45) NULL,
  `last_login` VARCHAR(45) NULL,
  `transaction_password` VARCHAR(45) NULL,
  `client_number` VARCHAR(45) NULL,
  PRIMARY KEY (`PK customer_id`),
  CONSTRAINT `fk_Customers_Ref_Customer_Types`
    FOREIGN KEY (`FK customer_type_code`)
    REFERENCES `mydb`.`Ref_Customer_Types` (`PK customer_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Addresses_Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Addresses_Types` (
  `PK address_type_code` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL DEFAULT 'Iz licne karte',
  PRIMARY KEY (`PK address_type_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Addresses` (
  `PK address_id` INT NOT NULL AUTO_INCREMENT,
  `FK address_type_code` INT NULL,
  `phone` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`PK address_id`),
  CONSTRAINT `fk_Addresses_Ref_Addresses_Types1`
    FOREIGN KEY (`FK address_type_code`)
    REFERENCES `mydb`.`Ref_Addresses_Types` (`PK address_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_Addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_Addresses` (
  `PK customer_addresses_id` INT NOT NULL AUTO_INCREMENT,
  `FK address_id` INT NULL,
  `FK customer_id` INT NULL,
  `date_from` DATE NULL,
  `date_to` DATE NULL,
  PRIMARY KEY (`PK customer_addresses_id`),
  CONSTRAINT `fk_Customer_Addresses_Addresses1`
    FOREIGN KEY (`FK address_id`)
    REFERENCES `mydb`.`Addresses` (`PK address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_Addresses_Customers1`
    FOREIGN KEY (`FK customer_id`)
    REFERENCES `mydb`.`Customers` (`PK customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Account_Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Account_Types` (
  `PK account_type_code` INT NOT NULL AUTO_INCREMENT,
  `descritption` VARCHAR(45) NULL DEFAULT 'Deposit',
  PRIMARY KEY (`PK account_type_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Currency_Codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Currency_Codes` (
  `PK currency_code` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`PK currency_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accounts` (
  `PK account_id` INT NOT NULL AUTO_INCREMENT,
  `FK account_type_code` INT NULL,
  `FK customer_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `date_opened` VARCHAR(45) NULL,
  `date_closed` VARCHAR(45) NULL,
  `current_ballance` VARCHAR(45) NULL,
  `other_details` VARCHAR(45) NULL,
  `FK currency_code` INT NULL,
  PRIMARY KEY (`PK account_id`),
  CONSTRAINT `fk_Accounts_Ref_Account_Types1`
    FOREIGN KEY (`FK account_type_code`)
    REFERENCES `mydb`.`Ref_Account_Types` (`PK account_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accounts_Customers1`
    FOREIGN KEY (`FK customer_id`)
    REFERENCES `mydb`.`Customers` (`PK customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accounts_Ref_Currency_Codes1`
    FOREIGN KEY (`FK currency_code`)
    REFERENCES `mydb`.`Ref_Currency_Codes` (`PK currency_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ballance_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ballance_History` (
  `PK ballance_date` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NULL,
  `ballance_at_date` VARCHAR(45) NULL,
  PRIMARY KEY (`PK ballance_date`),
  CONSTRAINT `fk_Ballance_History_Accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`Accounts` (`PK account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Country_Codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Country_Codes` (
  `PK country_code` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NULL,
  PRIMARY KEY (`PK country_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Merchant_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Merchant_Category` (
  `PK category_code` INT NOT NULL AUTO_INCREMENT,
  `category_description` VARCHAR(45) NULL DEFAULT 'Kafic',
  PRIMARY KEY (`PK category_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Merchants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Merchants` (
  `PK merchant_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK country_code` INT NULL,
  `FK category_code` INT NULL,
  PRIMARY KEY (`PK merchant_id`),
  CONSTRAINT `fk_Merchants_Ref_Country_Codes1`
    FOREIGN KEY (`FK country_code`)
    REFERENCES `mydb`.`Ref_Country_Codes` (`PK country_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Merchants_Ref_Merchant_Category1`
    FOREIGN KEY (`FK category_code`)
    REFERENCES `mydb`.`Ref_Merchant_Category` (`PK category_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Service_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Service_Type` (
  `PK service_type_code` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`PK service_type_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Products_and_Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products_and_Services` (
  `PK service_code` INT NOT NULL AUTO_INCREMENT,
  `FK merchant_id` INT NULL,
  `FK service_type_id` INT NULL,
  PRIMARY KEY (`PK service_code`),
  CONSTRAINT `fk_Products_and_Services_Merchants1`
    FOREIGN KEY (`FK merchant_id`)
    REFERENCES `mydb`.`Merchants` (`PK merchant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Products_and_Services_Ref_Service_Type1`
    FOREIGN KEY (`FK service_type_id`)
    REFERENCES `mydb`.`Ref_Service_Type` (`PK service_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Loan_Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Loan_Types` (
  `PK loan_type_code` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`PK loan_type_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Branches` (
  `PK branch_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `assets` VARCHAR(45) NULL,
  PRIMARY KEY (`PK branch_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loans` (
  `PK loan_id` INT NOT NULL AUTO_INCREMENT,
  `FK loan_type_code` INT NULL,
  `FK branch_id` INT NULL,
  `FK  service_type_code` INT NULL,
  `FK account_id` INT NULL,
  `inetrest_rate` VARCHAR(45) NULL,
  `borrowed` VARCHAR(45) NULL,
  `period` VARCHAR(45) NULL,
  `mortgage` VARCHAR(45) NULL,
  `request_date` VARCHAR(45) NULL,
  `approved_date` VARCHAR(45) NULL,
  `settlement` VARCHAR(45) NULL,
  `guarantor` VARCHAR(45) NULL,
  `repayment_plan` VARCHAR(45) NULL,
  `contract` VARCHAR(45) NULL,
  `date_contract_starts` VARCHAR(45) NULL,
  `date_contract_ends` VARCHAR(45) NULL,
  PRIMARY KEY (`PK loan_id`),
  CONSTRAINT `fk_Loan_Ref_Loan_Types1`
    FOREIGN KEY (`FK loan_type_code`)
    REFERENCES `mydb`.`Ref_Loan_Types` (`PK loan_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loan_Branch1`
    FOREIGN KEY (`FK branch_id`)
    REFERENCES `mydb`.`Branches` (`PK branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loan_Ref_Service_Type1`
    FOREIGN KEY (`FK  service_type_code`)
    REFERENCES `mydb`.`Ref_Service_Type` (`PK service_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loans_Accounts1`
    FOREIGN KEY (`FK account_id`)
    REFERENCES `mydb`.`Accounts` (`PK account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Card_Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Card_Types` (
  `PK card_type_code` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`PK card_type_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cards` (
  `PK card_id` INT NOT NULL AUTO_INCREMENT,
  `FK card_type_code` INT NULL,
  `FK  service_type_code` INT NULL,
  `FK account_id` INT NULL,
  `FK currency_code` INT NULL,
  PRIMARY KEY (`PK card_id`),
  CONSTRAINT `fk_Card_Ref_Card_Types1`
    FOREIGN KEY (`FK card_type_code`)
    REFERENCES `mydb`.`Ref_Card_Types` (`PK card_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_Ref_Service_Type1`
    FOREIGN KEY (`FK  service_type_code`)
    REFERENCES `mydb`.`Ref_Service_Type` (`PK service_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cards_Accounts1`
    FOREIGN KEY (`FK account_id`)
    REFERENCES `mydb`.`Accounts` (`PK account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cards_Ref_Currency_Codes1`
    FOREIGN KEY (`FK currency_code`)
    REFERENCES `mydb`.`Ref_Currency_Codes` (`PK currency_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_Purchase` (
  `PK purchase_id` INT NOT NULL AUTO_INCREMENT,
  `FK customer_id` INT NULL,
  `FK service_code` INT NULL,
  `purchase_date` VARCHAR(45) NULL,
  `quantity` VARCHAR(45) NULL,
  `other_details` VARCHAR(45) NULL,
  PRIMARY KEY (`PK purchase_id`),
  CONSTRAINT `fk_Customer_Purchase_Customers1`
    FOREIGN KEY (`FK customer_id`)
    REFERENCES `mydb`.`Customers` (`PK customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_Purchase_Products_and_Services1`
    FOREIGN KEY (`FK service_code`)
    REFERENCES `mydb`.`Products_and_Services` (`PK service_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Parties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parties` (
  `PK party_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`PK party_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Transaction_Types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Transaction_Types` (
  `PK transaction_type_code` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`PK transaction_type_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction_Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transaction_Messages` (
  `PK message_id` INT NOT NULL AUTO_INCREMENT,
  `FK  party_id` INT NULL,
  `FK account_id` INT NULL,
  `FK counterparty_id` INT NULL,
  `FK transaction_type_code` INT NULL,
  PRIMARY KEY (`PK message_id`),
  CONSTRAINT `fk_Transaction_Messages_Parties1`
    FOREIGN KEY (`FK  party_id`)
    REFERENCES `mydb`.`Parties` (`PK party_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_Messages_Accounts1`
    FOREIGN KEY (`FK account_id`)
    REFERENCES `mydb`.`Accounts` (`PK account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_Messages_Parties2`
    FOREIGN KEY (`FK counterparty_id`)
    REFERENCES `mydb`.`Parties` (`PK party_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_Messages_Ref_Transaction_Types1`
    FOREIGN KEY (`FK transaction_type_code`)
    REFERENCES `mydb`.`Ref_Transaction_Types` (`PK transaction_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transactions` (
  `PK transaction_id` INT NOT NULL AUTO_INCREMENT,
  `FK account_id` INT NULL,
  `FK purchase_id` INT NULL,
  `FK  transaction_type_code` INT NULL,
  `FK message_id` INT NULL,
  `FK related_ transaction_id` INT NULL,
  `other_details` VARCHAR(45) NULL,
  `FK currency_code` INT NULL,
  `date_of_transaction` VARCHAR(45) NULL,
  `amount` VARCHAR(45) NULL,
  PRIMARY KEY (`PK transaction_id`),
  CONSTRAINT `fk_Transactions_Accounts1`
    FOREIGN KEY (`FK account_id`)
    REFERENCES `mydb`.`Accounts` (`PK account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions_Customer_Purchase1`
    FOREIGN KEY (`FK purchase_id`)
    REFERENCES `mydb`.`Customer_Purchase` (`PK purchase_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions_Ref_Transaction_Types1`
    FOREIGN KEY (`FK  transaction_type_code`)
    REFERENCES `mydb`.`Ref_Transaction_Types` (`PK transaction_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions_Transaction_Messages1`
    FOREIGN KEY (`FK message_id`)
    REFERENCES `mydb`.`Transaction_Messages` (`PK message_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions_Transactions1`
    FOREIGN KEY (`FK related_ transaction_id`)
    REFERENCES `mydb`.`Transactions` (`PK transaction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transactions_Ref_Currency_Codes1`
    FOREIGN KEY (`FK currency_code`)
    REFERENCES `mydb`.`Ref_Currency_Codes` (`PK currency_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Bankers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bankers` (
  `PK banker_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `FK customer_id` INT NULL,
  `FK branch_id` INT NULL,
  PRIMARY KEY (`PK banker_id`),
  CONSTRAINT `fk_Bankers_Customers1`
    FOREIGN KEY (`FK customer_id`)
    REFERENCES `mydb`.`Customers` (`PK customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bankers_Branch1`
    FOREIGN KEY (`FK branch_id`)
    REFERENCES `mydb`.`Branches` (`PK branch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Card_Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Card_Transactions` (
  `PK card_transaction_id` INT NOT NULL AUTO_INCREMENT,
  `authorisation_code` VARCHAR(45) NULL,
  `gratuity` VARCHAR(45) NULL,
  `pin_verified` VARCHAR(45) NULL,
  `comment` VARCHAR(45) NULL,
  `FK card_id` INT NULL,
  `FK merchant_id` INT NULL,
  `FK transaction_type_code` INT NULL,
  PRIMARY KEY (`PK card_transaction_id`),
  CONSTRAINT `fk_Card_Transactions_Cards1`
    FOREIGN KEY (`FK card_id`)
    REFERENCES `mydb`.`Cards` (`PK card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_Transactions_Merchants1`
    FOREIGN KEY (`FK merchant_id`)
    REFERENCES `mydb`.`Merchants` (`PK merchant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_Transactions_Ref_Transaction_Types1`
    FOREIGN KEY (`FK transaction_type_code`)
    REFERENCES `mydb`.`Ref_Transaction_Types` (`PK transaction_type_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
