-- MySQL Script generated by MySQL Workbench
-- Sun Aug 18 00:06:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account` (
  `PK_account_id` INT NOT NULL AUTO_INCREMENT,
  `FK_account_type_id` INT NULL,
  `FK_customer_id` INT NULL,
  `account_name` VARCHAR(45) NULL,
  `acount_date_opened` VARCHAR(45) NULL,
  `acount_date_closed` VARCHAR(45) NULL,
  `acount_current_ballance` VARCHAR(45) NULL,
  `acount_other_details` VARCHAR(45) NULL,
  `FK_currency_code` INT NULL,
  `FK_account_status_id` INT NULL,
  PRIMARY KEY (`PK_account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `PK_address_id` INT NOT NULL AUTO_INCREMENT,
  `FK address_type_id` INT NULL,
  `phone` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_address_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ballance_History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ballance_History` (
  `PK_ ballance_date` INT NOT NULL AUTO_INCREMENT,
  `FK_account_id` INT NULL,
  `ballance_at_date` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_ ballance_date`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Banker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Banker` (
  `PK_banker_id` INT NOT NULL AUTO_INCREMENT,
  `banker_name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `banker_email` VARCHAR(45) NULL,
  `FK_ customer_id` INT NULL,
  `FK_ branch_id` INT NULL,
  PRIMARY KEY (`PK_banker_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Branch` (
  `PK_ branch_id` INT NOT NULL AUTO_INCREMENT,
  `branch_name` VARCHAR(45) NULL,
  `branch_city` VARCHAR(45) NULL,
  `branch_assets` VARCHAR(45) NULL,
  `FK_branch_type` INT NULL,
  PRIMARY KEY (`PK_ branch_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Card` (
  `PK_card_id` INT NOT NULL AUTO_INCREMENT,
  `FK_card_type_id` INT NULL,
  `FK _service_type_id` INT NULL,
  `FK_account_id` INT NULL,
  `FK_currency_code` INT NULL,
  PRIMARY KEY (`PK_card_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Card_Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Card_Transaction` (
  `PK_card_transaction_id` INT NOT NULL AUTO_INCREMENT,
  `card_authorisation_code` VARCHAR(45) NULL,
  `card_gratuity` VARCHAR(45) NULL,
  `card_pin_verified` VARCHAR(45) NULL,
  `card_transaction_comment` VARCHAR(45) NULL,
  `FK_card_id` INT NULL,
  `FK_merchant_id` INT NULL,
  `FK_ transaction_type_id` INT NULL,
  PRIMARY KEY (`PK_card_transaction_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contract` (
  `PK_contract_id` INT NOT NULL AUTO_INCREMENT,
  `date_starts` VARCHAR(45) NULL,
  `date_ends` VARCHAR(45) NULL,
  `contract_text` VARCHAR(45) NULL,
  `contract_registry_number` VARCHAR(45) NULL,
  `FK_contract_type_id` INT NULL,
  `FK_contract_status_code_id` INT NULL,
  `FK customer_id` INT NULL,
  PRIMARY KEY (`PK_contract_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `PK_customer_id` INT NOT NULL AUTO_INCREMENT,
  `FK_customer_type_id` INT NULL,
  `customer_name` VARCHAR(45) NULL,
  `customer_surname` VARCHAR(45) NULL,
  `customer_phone` VARCHAR(45) NULL,
  `customer_email` VARCHAR(45) NULL,
  `date_became_customer` DATE NULL,
  `date_quit_customer` DATE NULL,
  `other_details` VARCHAR(45) NULL,
  `customer_last_login` VARCHAR(45) NULL,
  `customer_transaction_password` VARCHAR(45) NULL,
  `customer_client_number` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_Address` (
  `PK_customer_addresses_id` INT NOT NULL AUTO_INCREMENT,
  `FK_address_id` INT NULL,
  `FK_customer_id` INT NULL,
  `date_from` DATE NULL,
  `date_to` DATE NULL,
  PRIMARY KEY (`PK_customer_addresses_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_Purchase` (
  `PK_ purchase_id` INT NOT NULL AUTO_INCREMENT,
  `FK_customer_id` INT NULL,
  `FK service_code` INT NULL,
  `purchase_date` VARCHAR(45) NULL,
  `purchase_quantity` VARCHAR(45) NULL,
  `purchase_other_details` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_ purchase_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loan` (
  `PK_ loan_id` INT NOT NULL AUTO_INCREMENT,
  `FK_loan_type_id` INT NULL,
  `FK_ branch_id` INT NULL,
  `FK _service_type_id` INT NULL,
  `FK_account_id` INT NULL,
  `loan_inetrest_rate` VARCHAR(45) NULL,
  `loan_borrowed` VARCHAR(45) NULL,
  `loan_period` VARCHAR(45) NULL,
  `mortgage` VARCHAR(45) NULL,
  `loan_request_date` VARCHAR(45) NULL,
  `loan_approved_date` VARCHAR(45) NULL,
  `loan_guarantor` VARCHAR(45) NULL,
  `loan_repayment_plan` VARCHAR(45) NULL,
  `date_contract_starts` VARCHAR(45) NULL,
  `date_contract_ends` VARCHAR(45) NULL,
  `FK_contract_id` INT NULL,
  PRIMARY KEY (`PK_ loan_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Merchant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Merchant` (
  `PK_merchant_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FK_country_code` INT NULL,
  `FK_ category_code` INT NULL,
  PRIMARY KEY (`PK_merchant_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Party` (
  `PK_party_id` INT NOT NULL AUTO_INCREMENT,
  `party_name` VARCHAR(45) NULL,
  `party_phone` VARCHAR(45) NULL,
  `party_email` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_party_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Payment` (
  `PK_payment_id` INT NOT NULL,
  `payment_date` VARCHAR(45) NULL,
  `payment_amount` VARCHAR(45) NULL,
  `FK_contract_id` INT NULL,
  `FK_payment_type` INT NULL,
  PRIMARY KEY (`PK_payment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Product_and_Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_and_Service` (
  `PK_service_code` INT NOT NULL AUTO_INCREMENT,
  `FK_ merchant_id` INT NULL,
  `FK_ service_type_id` INT NULL,
  PRIMARY KEY (`PK_service_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Account_Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Account_Status` (
  `PK_account_status_id` INT NOT NULL,
  `account_status_description` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_account_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Account_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Account_Type` (
  `PK account_type_id` INT NOT NULL AUTO_INCREMENT,
  `descritption` VARCHAR(45) NULL DEFAULT 'Deposit',
  PRIMARY KEY (`PK account_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Address_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Address_Type` (
  `PK_address_type_id` INT NOT NULL AUTO_INCREMENT,
  `address_description` VARCHAR(45) NULL DEFAULT 'Iz licne karte',
  PRIMARY KEY (`PK_address_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Branch_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Branch_Type` (
  `PK_branch_type` INT NOT NULL,
  `branch_type_description` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_branch_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Card_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Card_Type` (
  `PK_card_type_code` INT NOT NULL AUTO_INCREMENT,
  `card_type_description` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_card_type_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Contract_Status_Code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Contract_Status_Code` (
  `PK_contract_status_code_id` INT NOT NULL,
  `contract_status_description` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_contract_status_code_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Contract_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Contract_Type` (
  `PK_contract_type` INT NOT NULL,
  `contract_type_description` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_contract_type`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Country_Code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Country_Code` (
  `PK_ country_code` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_ country_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Currency_Code`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Currency_Code` (
  `PK_currency_code` INT NOT NULL AUTO_INCREMENT,
  `currency_code_description` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_currency_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Customer_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Customer_Type` (
  `PK_customer_type_id` INT NOT NULL AUTO_INCREMENT,
  `customer_type_description` VARCHAR(45) NULL DEFAULT 'Civil',
  PRIMARY KEY (`PK_customer_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Loan_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Loan_Type` (
  `PK_loan_type_id` INT NOT NULL AUTO_INCREMENT,
  `loan_type_description` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_loan_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Merchant_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Merchant_Category` (
  `PK category_id` INT NOT NULL AUTO_INCREMENT,
  `mcc_description` VARCHAR(45) NULL DEFAULT 'Kafic',
  `mcc_code` VARCHAR(45) NULL,
  PRIMARY KEY (`PK category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Payment_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Payment_Type` (
  `PK_payment_type_id` INT NOT NULL,
  `payment_type_description` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_payment_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Service_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Service_Type` (
  `PK service_type_id` INT NOT NULL AUTO_INCREMENT,
  `service_type_description` VARCHAR(45) NULL,
  PRIMARY KEY (`PK service_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Settlement_Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Settlement_Status` (
  `PK_settlement_status_id` INT NOT NULL,
  `settlement_status_description` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_settlement_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Settlement_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Settlement_Type` (
  `PK_settlement_type_id` INT NOT NULL,
  `settlement_description` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_settlement_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Transaction_Status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Transaction_Status` (
  `PK_transaction_status_id` INT NOT NULL,
  `transaction_status_description` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_transaction_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Ref_Transaction_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ref_Transaction_Type` (
  `PK_ transaction_type_id` INT NOT NULL AUTO_INCREMENT,
  `transaction_type_description` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_ transaction_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Settlement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Settlement` (
  `PK_settlement_id` INT NOT NULL,
  `date_deal` VARCHAR(45) NULL,
  `date_cancelled` VARCHAR(45) NULL,
  `settlement_text` VARCHAR(45) NULL,
  `settlement_amount` VARCHAR(45) NULL,
  `FK_settlement_type_id` INT NULL,
  `FK_settlement_status_id` INT NULL,
  `FK_contract_id` INT NULL,
  `FK_account_id` INT NULL,
  `FK_loan_id` INT NULL,
  PRIMARY KEY (`PK_settlement_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
  `PK_transaction_id` INT NOT NULL AUTO_INCREMENT,
  `FK_account_id` INT NULL,
  `FK_purchase_id` INT NULL,
  `FK_ transaction_type_id` INT NULL,
  `FK _transaction_message_id` INT NULL,
  `FK_related_ transaction_id` INT NULL,
  `other_details` VARCHAR(45) NULL,
  `FK_currency_id` INT NULL,
  `date_of_transaction` VARCHAR(45) NULL,
  `transaction_amount` VARCHAR(45) NULL,
  `FK_transaction_status_id` INT NULL,
  PRIMARY KEY (`PK_transaction_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction_Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transaction_Message` (
  `PK_message_id` INT NOT NULL AUTO_INCREMENT,
  `FK_ party_id` INT NULL,
  `FK_account_id` INT NULL,
  `FK_counterparty_id` INT NULL,
  `FK_ transaction_type_id` INT NULL,
  PRIMARY KEY (`PK_message_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
